-- Depuis Cergy

CREATE DATABASE LINK PAU
CONNECT TO remote_user IDENTIFIED BY 'password'
USING 'free';

-- Depuis PAU
CREATE DATABASE LINK CERGY
CONNECT TO remote_user IDENTIFIED BY 'password'
USING 'free';

-- Vues matérialisées sur Pau
-- On part du principe que les données ne sont pas critique et que l'on peut se permettre de faire des copies
-- identité
CREATE MATERIALIZED VIEW MV_PERMISSIONS
REFRESH FAST ON COMMIT
AS SELECT * FROM PERMISSIONS@CERGY;

CREATE MATERIALIZED VIEW MV_GROUPS
REFRESH FAST ON COMMIT
AS SELECT * FROM GROUPS@CERGY;

CREATE MATERIALIZED VIEW MV_USER_GROUP_PERMISSIONS
REFRESH FAST ON COMMIT
AS SELECT * FROM USER_GROUP_PERMISSIONS@CERGY;

CREATE MATERIALIZED VIEW MV_USER_GROUP
REFRESH FAST ON COMMIT
AS SELECT * FROM USER_GROUP@CERGY;

-- Infra

CREATE MATERIALIZED VIEW MV_LICENCE_DEVICE
REFRESH FAST ON COMMIT
AS SELECT * FROM LICENCE_DEVICE@CERGY;


-- Fragmentation horizontale
CREATE VIEW V_ALL_USERS 
AS SELECT * FROM GLPI_USER@CERGY
UNION
SELECT * FROM GLPI_USER@PAU;

CREATE VIEW V_ALL_LISCENCE_DEVICE
AS SELECT * FROM LICENCE_DEVICE@CERGY
UNION
SELECT * FROM MV_LICENCE_DEVICE@PAU;

-- finance ?