
-- Indexes (B-tree par défaut)
-- User Group

CREATE INDEX IDX_USER_GROUP_USER ON USER_GROUP(id_user);
CREATE INDEX IDX_USER_GROUP_GROUP ON USER_GROUP(id_group);

-- User Group Permissions
CREATE INDEX IDX_UGP_USER ON USER_GROUP_PERMISSIONS(id_user);
CREATE INDEX IDX_UGP_GROUP ON USER_GROUP_PERMISSIONS(id_group);
CREATE INDEX IDX_UGP_PERMISSION ON USER_GROUP_PERMISSIONS(id_permission);
