BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_group_permissions_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE seq_group_permissions_id
    START WITH 1
    INCREMENT BY 1
    NOCACHE;



-- Séquence pour GLPI_USER
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_vm_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
            RAISE;
        END IF;
END;
/
CREATE SEQUENCE seq_vm_id
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- Séquence pour GLPI_USER
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_glpi_user_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
            RAISE;
        END IF;
END;
/
CREATE SEQUENCE seq_glpi_user_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour GROUPS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_groups_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_groups_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour PERMISSIONS
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_permissions_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_permissions_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour PROJECT
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_project_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_project_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour NETWORK
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_network_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_network_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour LICENCE_DEVICE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_licence_device_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_licence_device_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour DEVICE
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_device_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_device_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour PERIPHERAL
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_peripheral_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_peripheral_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- Séquence pour tickets
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ticket_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_ticket_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Séquence pour interventions
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq_intervention_id';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/
CREATE SEQUENCE seq_intervention_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;