-- =======================
-- TEST 2 : AVEC INDEX ET CLUSTER
-- =======================



-- Activation du chronomètre Oracle
SET TIMING ON;

-- Nettoyage de PLAN_TABLE si déjà existante
DROP TABLE PLAN_TABLE PURGE;
CREATE TABLE PLAN_TABLE AS SELECT * FROM SYS.PLAN_TABLE$;

-- ANALYSE DE LA REQUÊTE (AVEC INDEX + CLUSTER)
PROMPT ===== PLAN D'EXECUTION AVEC INDEX ET CLUSTER =====
EXPLAIN PLAN SET STATEMENT_ID = 'with_index_cluster' FOR
SELECT d.id, p.description
FROM DEVICE d
JOIN PERIPHERAL p ON d.id = p.id_device
WHERE p.type = 'clavier';

SELECT STATEMENT_ID, OPERATION, OPTIONS, OBJECT_NAME, ID, PARENT_ID
FROM PLAN_TABLE
WHERE STATEMENT_ID = 'with_index_cluster';

-- MISE À JOUR DES STATISTIQUES
ANALYZE TABLE DEVICE COMPUTE STATISTICS FOR ALL INDEXES;
ANALYZE TABLE PERIPHERAL COMPUTE STATISTICS FOR ALL INDEXES;

-- MESURE DU TEMPS D'EXECUTION REEL
SET AUTOTRACE ON STATISTICS;
SELECT d.id, p.description
FROM DEVICE d
JOIN PERIPHERAL p ON d.id = p.id_device
WHERE p.type = 'clavier';
SET AUTOTRACE OFF;