-- Permission sur les Materialized Views
GRANT SELECT ON MV_PERMISSIONS TO Client;
GRANT SELECT ON MV_GROUPS TO Client;
GRANT SELECT ON MV_USER_GROUP_PERMISSIONS TO Client;
GRANT SELECT ON MV_USER_GROUP TO Client;
GRANT SELECT ON MV_LICENCE_DEVICE TO Client;

GRANT INSERT ON MV_LICENCE_DEVICE TO Technical_manager;