-- a exécuté après la création des roles


GRANT UPDATE, DELETE, INSERT, SELECT ON NETWORK to Network_technician;

GRANT UPDATE, DELETE, INSERT, SELECT ON DEVICE TO Machine_technician;
GRANT UPDATE, DELETE, INSERT, SELECT ON PERIPHERAL TO Machine_technician;
GRANT UPDATE, DELETE, INSERT, SELECT ON VM TO Machine_technician;
GRANT UPDATE, DELETE, INSERT, SELECT ON LICENCE_DEVICE TO Machine_technician;
GRANT SELECT, DELETE, UPDATE, INSERT ON PERMISSIONS TO Admin;

GRANT INSERT ON DEVICE TO Technical_manager;
GRANT INSERT ON PERIPHERAL TO Technical_manager;
GRANT INSERT ON VM TO Technical_manager;
GRANT INSERT ON LICENCE_DEVICE TO Technical_manager;


GRANT SELECT ON TICKET TO Accountant;
GRANT SELECT ON PROJECT TO Accountant;
GRANT UPDATE, DELETE, INSERT, SELECT ON TICKET TO Project_manager;
GRANT UPDATE, DELETE, INSERT, SELECT ON PROJECT TO Project_manager;
GRANT UPDATE, DELETE, INSERT, SELECT ON INTERVENTION TO Project_manager;

GRANT UPDATE ON INTERVENTION TO Technical_manager;

GRANT INSERT ON TICKET TO Client;

GRANT SELECT ON PERIPHERAL TO Client;
GRANT SELECT ON DEVICE TO Client;
GRANT SELECT ON VM TO Client;
GRANT SELECT ON LICENCE_DEVICE TO Client;


-- Permissions sur les vues
GRANT SELECT ON Prix_Device TO Accountant;
GRANT SELECT ON Prix_Peripheral TO Accountant;
GRANT SELECT ON Prix_Licence TO Accountant;
GRANT SELECT ON Prix_Intervention TO Accountant;
GRANT SELECT ON MV_ALL_DEVICES TO Technical_manager;