-- Tablespace
CREATE TABLESPACE User_group 
DATAFILE 'user_group.dbf' 
SIZE 50M 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE Device_network
DATAFILE 'device_network.dbf' 
SIZE 50M 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE Project_management 
DATAFILE 'project_management.dbf' 
SIZE 50M 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
