alter session set "_ORACLE_SCRIPT"=true;




DROP TABLE AFFECTATION;
DROP TABLE INTERVENTION;
DROP TABLE TICKET;
DROP TABLE PROJECT;
DROP TABLE GLPI_USER;
DROP TABLE VM;
DROP TABLE PERIPHERAL;
DROP TABLE DEVICE;
DROP TABLE NETWORK;
DROP TABLE LICENCE_DEVICE;


-- Création des TABLES
CREATE TABLE PERIPHERAL (
    id NUMBER PRIMARY KEY,
    description VARCHAR2(255),
    type VARCHAR2(50),
    price NUMBER,
    buying_date DATE,
    id_device NUMBER
) TABLESPACE Device_network;

CREATE TABLE VM (
    id NUMBER PRIMARY KEY,
    description VARCHAR2(255),
    id_device NUMBER NOT NULL
) TABLESPACE Device_network;

CREATE TABLE DEVICE (
    id NUMBER PRIMARY KEY,
    description VARCHAR2(255),
    type VARCHAR2(50),
    price NUMBER,
    ip_address VARCHAR2(50),
    buying_date DATE,
    guaranty_expiration_date DATE,
    id_network NUMBER,
    id_licence_device NUMBER
) TABLESPACE Device_network;

CREATE TABLE NETWORK (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    alias VARCHAR2(100),
    ip_address VARCHAR2(50),
    ip_mask VARCHAR2(50)
) TABLESPACE Device_network;

CREATE TABLE LICENCE_DEVICE (
    id NUMBER PRIMARY KEY,
    price NUMBER,
    expiration_date DATE,
    buying_date DATE,
    id_device NUMBER
) TABLESPACE Device_network;

CREATE TABLE INTERVENTION (
    id NUMBER PRIMARY KEY,
    inter_date DATE,
    price NUMBER,
    description VARCHAR2(255),
    type VARCHAR2(50),
    id_device NUMBER NOT NULL
) TABLESPACE Project_management;

CREATE TABLE AFFECTATION (
    id NUMBER PRIMARY KEY,
    date_affectation DATE,
    id_user NUMBER NOT NULL,
    id_intervention NUMBER NOT NULL,
    id_ticket NUMBER NOT NULL
) TABLESPACE Project_management;

CREATE TABLE TICKET (
    id NUMBER PRIMARY KEY,
    subject VARCHAR2(255),
    description VARCHAR2(255),
    statut VARCHAR2(50) DEFAULT 'OPEN',
    ticket_creation_date DATE DEFAULT SYSDATE,
    id_created_by NUMBER,
    id_project NUMBER
) TABLESPACE Project_management;

CREATE TABLE GLPI_USER (
    id NUMBER PRIMARY KEY,
    last_name VARCHAR2(100),
    first_name VARCHAR2(100)
) TABLESPACE User_group;

CREATE TABLE PROJECT (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    description VARCHAR2(255),
    creation_date DATE DEFAULT SYSDATE
) TABLESPACE Project_management;



-- Ajout des contraintes
-- Peripheral
ALTER TABLE PERIPHERAL
ADD CONSTRAINT FK_PERIPHERAL_DEVICE FOREIGN KEY (id_device)
REFERENCES DEVICE(id);

-- Device
ALTER TABLE DEVICE
ADD CONSTRAINT FK_DEVICE_LICENCE FOREIGN KEY (id_licence_device)
REFERENCES LICENCE_DEVICE(id);

ALTER TABLE DEVICE
ADD CONSTRAINT FK_DEVICE_NETWORK FOREIGN KEY (id_network)
REFERENCES NETWORK(id);

-- Intervention
ALTER TABLE INTERVENTION
ADD CONSTRAINT FK_INTERVENTION_DEVICE FOREIGN KEY (id_device)
REFERENCES DEVICE(id);

-- Affectation
ALTER TABLE AFFECTATION
ADD CONSTRAINT FK_AFFECTATION_USER FOREIGN KEY (id_user)
REFERENCES GLPI_USER(id);

ALTER TABLE AFFECTATION
ADD CONSTRAINT FK_AFFECTATION_INTERVENTION FOREIGN KEY (id_intervention)
REFERENCES INTERVENTION(id);

ALTER TABLE AFFECTATION
ADD CONSTRAINT FK_AFFECTATION_TICKET FOREIGN KEY (id_ticket)
REFERENCES TICKET(id);

-- Ticket
ALTER TABLE TICKET
ADD CONSTRAINT FK_TICKET_USER FOREIGN KEY (id_created_by)
REFERENCES GLPI_USER(id);

ALTER TABLE TICKET
ADD CONSTRAINT FK_TICKET_PROJECT FOREIGN KEY (id_project)
REFERENCES PROJECT(id);

COMMIT;